version: "3"

services:
  db:
    image: postgres:10

  api:
    build: .
    command: fresh
    environment:
      - DB_URI=postgres://postgres@db/?sslmode=disable
    links:
      - db
    ports:
      - 4273:4273
    volumes:
      - .:/go/src/github.com/8-team/bacotto
