version: "3"

services:
  db:
    image: postgres:10

  api:
    build: .
    command: fresh -c /go/src/github.com/8-team/bacotto/res/fresh.conf
    environment:
      - DB_URI=postgres://postgres@db/?sslmode=disable
      - SERIALS_DB_URI
      - BOTTO_API_TOKEN
    links:
      - db
    ports:
      - 4273:443
    volumes:
      - .:/go/src/github.com/8-team/bacotto
